In [1]:
import os

#1.generating a vector of inputs and a vector of weights

In [5]:
import numpy as np
np.random.seed(seed=0)
X = np.random.choice([0,1], 2)
W = np.random.choice([-1,1], 2)
print(f'Input vector:{X}, Weight vector:{W}')

Input vector:[0 1], Weight vector:[ 1 -1]


#2. computing the dot product between the vector of inputs and weight

In [6]:
dot = X @ W
print(f'Dot product: {dot}')

Dot product: -1


#3. Defining the Threshold Activation Function

In [7]:
def linear_threshold_gate(dot: int, T: float) -> int:
    '''Returns the binary threshold output'''
    if dot >= T:
        return 1
    else:
        return 0

#4.a. Compute the output based on the threshold value(T=-1).

In [8]:
T = -1
activation = linear_threshold_gate(dot, T)
print(f'Activation: {activation}')

Activation: 1


#4.b. Compute the output based on the threshold value(T=0).

In [9]:
T = 0
activation = linear_threshold_gate(dot, T)
print(f'Activation: {activation}')

Activation: 0


#N size inputs MCP Neuron

In [10]:
input_size = 4

In [18]:
import numpy as np
import pandas as pd

class MCPNeuron(object):
  def __init__(self, w = [1,1], t = 1, gates= False):
        self.w = np.array(w)
        self.t = t
        self.gates = gates

  def predict(self, message):
        x = message # consistency with function notation above
        sum_ = np.inner(self.w,x)
        if not self.gates:
          if sum_ >= self.t:
              return "Activation : 1" , "Neuron Fires"
          else:
              return "Activation : 0" , "Neuron doesn't Fire"
        else:
          if sum_ >= self.t:
              return 1
          else:
              return 0

In [19]:
import numpy as np
np.random.seed(seed=0)
X = np.random.choice([0,1], input_size)# generate random vector X, sampling from {0,1}
W = np.random.choice([-1,1], input_size) # generate random vector W, sampling from {-1,1}
print(f'Input vector:{X}, Weight vector:{W}')

Input vector:[0 1 1 0], Weight vector:[1 1 1 1]


In [22]:
mcp_neuron = MCPNeuron(W, t=2)


In [23]:
mcp_neuron.predict(X)

('Activation : 1', 'Neuron Fires')

#truth table generation

In [26]:
def TruthTable(object, input, input_labels, output_labels):
    table = pd.DataFrame(input, columns = input_labels)

    out_signals = []
    for row in input:
        signal = object.predict(message = row)
        out_signals.append(signal)

    table[output_labels] = pd.Series(out_signals)
    return table

#OR function implimentation
* The OR function is “activated” even when only one of incoming inputs is “on”, this is, it outputs is 0 only when all inputs are 0.
* In “neural” terms, the neuron fires when one of the incoming signals is excitatory. On a more abstract level, think in a situation where you would decide that something is “true” or you would say “yes”, depending on the value of some “conditions” or “variables”.
* This relationship is expressed in table below:

<center>

| ${x_1}$           | $x_2$    | $y$   |
| :---------------: | :------: | :---: |
| 0                 |   0      | 0     |
| 0                 |   1      | 1     |
| 1                 |   0      | 1     |
| 1                 |   1      | 1     |

</center>

The OR gate is a logic gate which returns true (1) even if one of its input signals are true (1).
* Weights: $w_1 = 1, w_2 = 1$
* Threshold: $t=1$

In [27]:
in_labels = ['x1', 'x2']
out_label = 'y'


in_signals = np.array([
    [0,0], # both no
    [0,1], # one no, one yes
    [1,0], # one yes, one no
    [1,1]  # bot yes
])

print(in_signals)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [28]:
#Assign weights
or_weights = np.array([1,1])
# Assign Threshold
or_threshold = 1
print(f'Weights: {or_weights} \nThreshold:{or_threshold}')

Weights: [1 1] 
Threshold:1


In [29]:
# instantiate AND gate as an MCP Neuron class
OR = MCPNeuron(or_weights,or_threshold, "True")

In [31]:
OR_table = TruthTable(OR ,in_signals,in_labels,out_label)

In [33]:
print(OR_table)

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1


#AND Function implimetation

* The AND function is “activated” only when all the incoming inputs are “on”, this is, it outputs is 1 only when all inputs are 1.
* In “neural” terms, the neuron fires when all the incoming signals are excitatory. On a more abstract level, think in a situation where you would decide that something is “true” or you would say “yes”, depending on the value of some “conditions” or “variables”.
* This relationship is expressed in table below:

<center>

| ${x_1}$           | $x_2$    | $y$   |
| :---------------: | :------: | :---: |
| 0                 |   0      | 0     |
| 0                 |   1      | 0     |
| 1                 |   0      | 0     |
| 1                 |   1      | 1     |

</center>

The AND gate is a logic gate which returns true (1) only if both of its input signals are true (1).
* Weights: $w_1 = 1, w_2 = 1$
* Threshold: $t=2$

In [34]:
in_labels = ['x1', 'x2']
out_label = 'y'


in_signals = np.array([
    [0,0], # both no
    [0,1], # one no, one yes
    [1,0], # one yes, one no
    [1,1]  # bot yes
])

print(in_signals)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [35]:
#Assign weights
and_weights = np.array([1,1])
# Assign Threshold
and_threshold =2
print(f'Weights: {and_weights} \nThreshold:{and_threshold}')

Weights: [1 1] 
Threshold:2


In [36]:
# Assign Threshold
and_threshold = 2
print(and_threshold)

2


In [37]:
# instantiate AND gate as an MCP Neuron class
AND = MCPNeuron(and_weights,and_threshold, "True")

In [39]:
AND_table = TruthTable(AND ,in_signals,in_labels,out_label)

In [40]:
print(AND_table)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


#NOR Function implimentation
* This relationship is expressed in table below:

<center>

| ${x_1}$           | $x_2$    | $y$   |
| :---------------: | :------: | :---: |
| 0                 |   0      | 1     |
| 0                 |   1      | 0     |
| 1                 |   0      | 0     |
| 1                 |   1      | 0     |

</center>

The OR gate is a logic gate which returns true (1) even if one of its input signals are true (1).
* Weights: $w_1 = -1, w_2 = -1$
* Threshold: $t=0$

In [41]:
in_labels = ['x1', 'x2']
out_label = 'y'


in_signals = np.array([
    [0,0], # both no
    [0,1], # one no, one yes
    [1,0], # one yes, one no
    [1,1]  # bot yes
])

print(in_signals)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [42]:
#Assign weights
nor_weights = np.array([-1,-1])
# Assign Threshold
nor_threshold = 0
print(f'Weights: {nor_weights} \nThreshold:{nor_threshold}')

Weights: [-1 -1] 
Threshold:0


In [43]:
# instantiate AND gate as an MCP Neuron class
NOR = MCPNeuron(nor_weights,nor_threshold, "True")

In [47]:
NOR_table = TruthTable(NOR ,in_signals,in_labels,out_label)
print(NOR_table)

   x1  x2  y
0   0   0  1
1   0   1  0
2   1   0  0
3   1   1  0
